---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- 'App Store'
- Calendar
- Contacts
- FaceTime
- Mail
- Maps
- Messages
- Music
- Photos
- Podcasts
- Reminders
- Safari
- Settings
- TV

dockitems_persist:
-  name: "Calendar"
   path: "/Applications/Calendar.app/"
   pos: 3

 - name: "Home"
   path: "/Applications/Home.app/"
   pos: 4
   
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
   pos: 5
   
 - name: "Spotify"
   path: "/Applications/Spotify.app/"
   pos: 6
   
 - name: "Telegram" 
   path: "/Applications/Telegram.app/"
   pos: 7
   
 - name: "VK Messenger"
   path: "/Applications/VK Messenger.app/"
   pos: 8
   
 - name: "Trello"
   path: "/Applications/Trello.app/"
   pos: 9
   
 - name: "Terminal"
   path: "/Applications/Utilities/Terminal.app"
   pos: 10
   
 - name: "Sublime Text"
   path: "/Applications/Sublime Text.app/"
   pos: 11

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/el1telordy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx

homebrew_installed_packages:
  - git
  - nmap
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aldente
  - alfred
  - android-platform-tools
  - balenaetcher
  - bitwarden
  - coconutbattery
  - discord
  - docker
  - google-chrome
  - impactor
  - intellij-idea
  - istat-menus
  - keka
  - moonlight
  - onyx
  - qbittorrent
  - spotify
  - sublime-text
  - syncthing
  - telegram-desktop
  - vk-messenger

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1278508951, name: "Trello" }
  - { id: 1265763895, name: "VK Messenger" }
  - { id: 1176074088, name: "Termius - SSH client" }
  - { id: 497799835, name: "Xcode" }
#   - { id: 1191449274, name: "ToothFairy" }
#   - { id: 441258766, name: "Magnet" }
  - { id: 409201541, name: "Pages" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 1440147259, name: "AdGuard for Safari" }
  - { id: 975937182, name: "Fantastical - Calendar & Tasks" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
